### ISSUE TITLE
Missing package dependency for 'esm'

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/amplify-js-local#6]
Received the below errors when tried to use `amplifylocal --version`

```javascript
$ npm install -g amplify-js-local @aws-amplify/cli

added 27 packages, and audited 28 packages in 20s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```javascript
$ amplifylocal --version
node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module 'esm'
Require stack:
- C:\Users\marce\AppData\Roaming\npm\node_modules\amplify-js-local\bin\amplifylocal
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\marce\AppData\Roaming\npm\node_modules\amplify-js-local\bin\amplifylocal:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\marce\\AppData\\Roaming\\npm\\node_modules\\amplify-js-local\\bin\\amplifylocal'
  ]
}
```

Missing module: https://www.npmjs.com/package/esm

**Comment by whummer** [comment]
Should be fixed via #8 with help from @pinzon 👍 . Can you please confirm it works with the latest version `0.1.7` now @MarcelStranak ?

**Comment by MarcelStranak** [comment]
It appears to be installed correctly now. Thanks.
